---
title: "TCGA"
output: html_document
---

Import data
```{r}
tcga <- readr::read_rds('~/Desktop/tcga.rds')

#call tcga download function 
exp <- tcga[[1]]
cols <- tcga[[2]]
rows <- tcga[[3]]
rm(tcga)
```

Run tsne as a sanity check
```{r}
.norm.log.counts <- function(counts) {
  norm.fact <- colSums(counts)
  counts.norm <- t(apply(counts, 1, .norm, n = norm.fact))
  counts.log <- log2(counts.norm)
}

.norm <- function(x, n) {
  x / n * 1000000 + 1
}

#caluclate log cpm
cpm <- lapply(exp, .norm.log.counts)
rm(exp)

#find genes present in all expression data
genes <- lapply(cpm, rownames)
inCommon <- Reduce(intersect, genes)
  
#subset expression list to only include in common genes
cpmFiltered <- lapply(cpm, function(x) as.data.frame(x[rownames(x) %in% inCommon, ]))
rm(cpm)

#bind list
cpmMat <- as.matrix(dplyr::bind_cols(cpmFiltered))
rownames(cpmMat) <- inCommon
readr::write_rds(cpmMat, path = "~/Desktop/tcgaCPM.rds", compress = "bz2")
rm(cpmFiltered)

#coldata
colNames <- lapply(cols, colnames)
inCommon <- Reduce(intersect, colNames)
colsFiltered <- lapply(cols, function(x) as.data.frame(x[, colnames(x) %in% inCommon]))
colsMat <- dplyr::bind_rows(colsFiltered) %>%
  as_tibble() %>%
  readr::write_rds(path = "~/Desktop/colData.rds", compress = "bz2")

#select highly variable genes
RowVar <- function(x) {
  rowSums((x - rowMeans(x))^2)/(dim(x)[2] - 1)
}
rv <- RowVar(cpmMat)
select <- order(rv, decreasing = TRUE)[1:5000]

#calculate 1-pearson's
d <- as.dist(1-cor(cpmMat[select, ], method = "p"))

#tsne
tsne <- as.data.frame(Rtsne::Rtsne(d, is_distance = TRUE, perplexity = 50, max_iter = 5000)$Y)
leng <- unlist(lapply(cols, function(x) nrow(x)))
tsne$cancer <- rep(names(rows), leng)
tsne$AS <- cpmMat[rownames(cpmMat) == "ENSG00000234546", ]
tsne$HG <- cpmMat[rownames(cpmMat) == "ENSG00000228526", ]

#plot
col64 <- c(
"#000000", "#FFFF00", "#1CE6FF", "#FF34FF", "#FF4A46", "#008941", "#006FA6", "#A30059",
"#FFDBE5", "#7A4900", "#0000A6", "#63FFAC", "#B79762", "#004D43", "#8FB0FF", "#997D87",
"#5A0007", "#809693", "#FEFFE6", "#1B4400", "#4FC601", "#3B5DFF", "#4A3B53", "#FF2F80",
"#61615A", "#BA0900", "#6B7900", "#00C2A0", "#FFAA92", "#FF90C9", "#B903AA", "#D16100",
"#DDEFFF", "#000035", "#7B4F4B", "#A1C299", "#300018", "#0AA6D8", "#013349", "#00846F",
"#372101", "#FFB500", "#C2FFED", "#A079BF", "#CC0744", "#C0B9B2", "#C2FF99", "#001E09",
"#00489C", "#6F0062", "#0CBD66", "#EEC3FF", "#456D75", "#B77B68", "#7A87A1", "#788D66",
"#885578", "#FAD09F", "#FF8A9A", "#D157A0", "#BEC459", "#456648", "#0086ED", "#886F4C",
"#34362D", "#B4A8BD", "#00A6AA", "#452C2C", "#636375", "#A3C8C9", "#FF913F", "#938A81",
"#575329", "#00FECF", "#B05B6F", "#8CD0FF", "#3B9700", "#04F757", "#C8A1A1", "#1E6E00",
"#7900D7", "#A77500", "#6367A9", "#A05837", "#6B002C", "#772600", "#D790FF", "#9B9700",
"#549E79", "#FFF69F", "#201625", "#72418F", "#BC23FF", "#99ADC0", "#3A2465", "#922329",
"#5B4534", "#FDE8DC", "#404E55", "#0089A3", "#CB7E98", "#A4E804", "#324E72", "#6A3A4C")


ggplot(tsne, aes(V1, V2, colour = cancer)) + geom_point() + scale_colour_manual(values = col64)
ggplot(tsne, aes(V1, V2, colour = AS), alpha = 0.5) + geom_jitter() + viridis::scale_colour_viridis()
ggplot(tsne, aes(V1, V2, colour = HG)) + geom_point() + viridis::scale_colour_viridis()

#clinical
#find clinical in common
clin <- lapply(cols, colnames)
inCommon <- Reduce(intersect, clin)
clinFiltered <- lapply(cols, function(x) as.data.frame(x[, colnames(x) %in% inCommon]))
clinical <- dplyr::bind_rows(clinFiltered)

tsne$tumor_stage <- clinical$tumor_stage
tsne$vital_status <- clinical$vital_status
tsne$morphology <- clinical$morphology
tsne$days_to_death <- clinical$days_to_death
tsne$days_to_recurrence <- clinical$days_to_recurrence
tsne$tumor_grade <- clinical$tumor_grade
tsne$progression_or_recurrence <- clinical$progression_or_recurrence

tsne %>%
#  filter(!is.na(days_to_recurrence)) %>%
  ggplot(aes(V1, V2, colour = progression_or_recurrence), alpha = 0.5) + geom_jitter()

```

```{r}

##subset AS: ENSG00000234546, HG: ENSG00000228526 and calculate cpm


sub <- lapply(exp, function(x)
  x[rownames(x) %in% c("ENSG00000234546", "ENSG00000228526"), ]
)

cpm <- lapply(sub, .norm.log.counts)
cpmTibble <- lapply(cpm, function(x)
  tibble(
    sample = colnames(x),
    ENSG00000234546 = x[rownames(x) == "ENSG00000234546", ],
    ENSG00000228526 = x[rownames(x) == "ENSG00000228526", ]
  )
)

asDF <- bind_rows(cpmTibble)

#find patients with the days_to_death variable present
dtd <- lapply(cols, function(x)
  tibble(
    sample = rownames(x),
    days_to_death = as.numeric(x[, colnames(x) == "days_to_death"]),
    disease_type = as.character(x[, colnames(x) == "project_id"]),
    patient = as.character(x[, colnames(x) == "patient"]),
    days_to_last_follow_up = as.numeric(x[, colnames(x) == "days_to_last_follow_up"]),
    vital_status = as.character(x[, colnames(x) == "vital_status"])
  )
)

dtd <- bind_rows(dtd) %>%
  mutate(
    OS_time_to_event = case_when(
      vital_status == "alive" ~ days_to_last_follow_up,
      vital_status == "dead" ~ days_to_death
  ))

#add p53 mut status
p53in <- rjson::fromJSON(file = "~/Github/miR34a_asRNA_project/inst/SurvivalTCGA/files.2017-11-13T13_37_07.279347_p53mut.json" )
fileName <- sapply(p53in, `[[`, 1)
p53mutSamp <- gsub(
  "nationwidechildrens\\.org_biospecimen\\.(.*)\\.xml",
  "\\1",
  fileName
)

data <- dtd %>%
  mutate(p53 = if_else(patient %in% p53mutSamp, "mut", "wt")) %>%
  right_join(asDF)

#remove normal (non-tumor) samples
data <- data %>%
  filter(as.numeric(gsub("^.{13}(..).*", "\\1", pull(data, sample))) < 10)
```


look at normal vs tumor

survival
```{r}
#HG AS corr
data %>%
  select(p53, disease_type, ENSG00000228526, ENSG00000234546) %>%
  gather(gene, cpm, -p53, -disease_type) %>%
#filter(disease_type == "TCGA-UVM") %>%
  arrange(gene, cpm, p53) %>%
  group_by(disease_type, p53, gene) %>%
  mutate(tumour = row_number()) %>%
#mutate(cpm = scale(cpm, center = TRUE, scale = FALSE)) %>%
  filter(disease_type == "TCGA-STAD") %>%
  ggplot(aes(tumour, cpm, colour = gene)) +
    geom_point(aes(shape = p53)) +
    facet_grid(.~disease_type, scales = "free", space = "free")

#p53 plot
data %>%
  mutate(p53 = if_else(patient %in% p53mutSamp, "mut", "wt")) %>%
  filter(!is.na(days_to_death)) %>%
  group_by(disease_type) %>%
  filter(n_distinct(p53) == 2) %>%
  ungroup() %>%
  add_count(p53, disease_type) %>%
  group_by(disease_type) %>%
  filter(all(n > 5)) %>%
  ungroup() %>%
  mutate(p53 = parse_factor(p53, levels = c("wt", "mut"))) %>%
  ggplot(aes(p53, days_to_death, fill = disease_type)) +
    geom_boxplot() +
#geom_jitter() +
    guides(fill = FALSE) +
    facet_wrap(~ disease_type)

#p53 cor
data %>%
  mutate(p53 = if_else(patient %in% p53mutSamp, "mut", "wt")) %>%
  filter(!is.na(days_to_death)) %>%
  group_by(disease_type) %>%
  filter(n_distinct(p53) == 2) %>%
  ungroup() %>%
  add_count(p53, disease_type) %>%
  group_by(disease_type) %>%
  filter(all(n > 5)) %>%
  select(-n) %>%
  ungroup() %>%
  mutate(p53 = parse_factor(p53, levels = c("wt", "mut"))) %>%
  group_by(disease_type) %>%
  do(tidy(lm(days_to_death ~ p53, data = .))) %>%
  print(n = nrow(.))

#HG plot
data %>%
  mutate(p53 = if_else(patient %in% p53mutSamp, "mut", "wt")) %>%
  filter(!is.na(days_to_death)) %>%
  group_by(disease_type) %>%
  filter(n_distinct(p53) == 2) %>%
  ungroup() %>%
  add_count(p53, disease_type) %>%
  group_by(disease_type) %>%
  filter(all(n > 5)) %>%
  select(-n) %>%
  ungroup() %>%
  mutate(p53 = parse_factor(p53, levels = c("wt", "mut"))) %>%
  group_by(disease_type, p53) %>%
  mutate(
    quantile = ntile(ENSG00000228526, 10),
    group = case_when(
      quantile == 1 | quantile == 2 | quantile == 3 ~ "low",
      quantile == 8 | quantile == 9 | quantile == 10 ~ "high",
      TRUE ~ "middle"
    ),
    group = parse_factor(group, levels = c("low", "middle", "high")),
    n = n()
  ) %>%
  ungroup() %>%
#group_by(p53, group, disease_type) %>%
# filter(n_distinct(sample) < 10) %>%
  select(disease_type, p53, group) %>% table
  ggplot(aes(group, days_to_death, fill = p53)) +
    geom_boxplot() +
    facet_wrap(~disease_type)

#AS
data %>%
  mutate(p53 = if_else(patient %in% p53mutSamp, "mut", "wt")) %>%
  filter(!is.na(days_to_death)) %>%
  group_by(disease_type) %>%
  filter(n_distinct(p53) == 2) %>%
  ungroup() %>%
  add_count(p53, disease_type) %>%
  group_by(disease_type) %>%
  filter(all(n > 5)) %>%
  select(-n) %>%
  ungroup() %>%
  mutate(p53 = parse_factor(p53, levels = c("wt", "mut"))) %>%
  group_by(disease_type, p53) %>%
  mutate(
    quantile = ntile(ENSG00000234546, 10),
    group = case_when(
      quantile == 1 | quantile == 2 | quantile == 3 ~ "low",
      quantile == 8 | quantile == 9 | quantile == 10 ~ "high",
      TRUE ~ "middle"
    ),
    group = parse_factor(group, levels = c("low", "middle", "high")),
    n = n()
  ) %>%
  ungroup() %>%
#select(disease_type, p53, group) %>% table
  filter(disease_type == "TCGA-BLCA") %>%
  ggplot(aes(group, days_to_death, fill = p53)) +
    geom_boxplot() +
    facet_wrap(~disease_type) +
    scale_y_continuous(trans = "log2")

```
