---
title: "miR34a asRNA (lncTAM34a) project"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_depth: 3
    code_folding: hide
liftr:
  maintainer: "Jason Serviss"
  email: "jason.serviss@ki.se"
  from: "rocker/tidyverse:3.4.2"
  pandoc: false
  cran:
    - knitr/1.17
    - rmarkdown/1.6
    - printr/0.1
    - ggthemes/3.4.0
    - repmis/0.5
    - extrafont/0.17
    - scales/0.5.0
  remotes:
    - "GranderLab/miR34a_asRNA_project"
---

<style> 
.caption { 
  color: Black; 
  font-family: "Times New Roman", Times, serif;
  font-size: 1.0em; 
}
</style>

```{r, include = FALSE, message = FALSE}
library(miR34AasRNAproject)
library(knitr)

rmds <- fileMap("Rmd")
rmds <- rmds[names(rmds) != "All figures"]

out <- NULL
for (p in rmds) {
  out <- c(out, knit_child(system.file(p, package = "miR34AasRNAproject")))
}
names(out) <- names(rmds)
```


# Figure 1 {.tabset}

## Figure 1a

`r out["Figure 1a"]`

## Figure 1b

`r out["Figure 1b"]`

## Figure 1c

`r out["Figure 1c"]`

## Figure 1d

`r out["Figure 1d"]`

## Figure 1e

`r out["Figure 1e"]`

## Figure 1f

`r out["Figure 1f"]`

# Figure 2 {.tabset}

## Figure 2a

`r out["Figure 2a"]`

## Figure 2b

`r out["Figure 2b"]`

## Figure 2c

`r out["Figure 2c"]`

## Figure  2d

`r out["Figure 2d"]`

# Figure 3 {.tabset}

## Figure 3a

`r out["Figure 3a"]`

## Figure 3b

`r out["Figure 3b"]`

## Figure 3c

`r out["Figure 3c"]`

## Figure 3d

`r out["Figure 3d"]`

# Figure 4 {.tabset}

## Figure 4a

`r out["Figure 4a"]`

## Figure 4b

`r out["Figure 4b"]`

# Figure 5 {.tabset}

`r out["Figure 5"]`

# Supplementary Figure 1 {.tabset}

## Supplementary Figure 1a

`r out["Supplementary Figure 1a"]`

## Supplementary Figure 1b

`r out["Supplementary Figure 1b"]`

# Supplementary Figure 2 {.tabset}

## Supplementary Figure 2a

`r out["Supplementary Figure 2a"]`

## Supplementary Figure 2b

`r out["Supplementary Figure 2b"]`

## Supplementary Figure 2c

`r out["Supplementary Figure 2c"]`

## Supplementary Figure 2d

`r out["Supplementary Figure 2d"]`

## Supplementary Figure 2e

`r out["Supplementary Figure 2e"]`

# Supplementary Figure 3 {.tabset}

## Supplementary Figure 3a

`r out["Supplementary Figure 3a"]`

## Supplementary Figure 3b

`r out["Supplementary Figure 3b"]`

## Supplementary Figure 3c

`r out["Supplementary Figure 3c"]`

# Supplementary Figure 4 {.tabset}

## Supplementary Figure 4a

`r out["Supplementary Figure 4a"]`

## Supplementary Figure 4b

`r out["Supplementary Figure 4b"]`

## Supplementary Figure 4c

`r out["Supplementary Figure 4c"]`

# Supplementary Figure 5 {.tabset}

`r out["Supplementary Figure 5"]`

# Supplementary Figure 6 {.tabset}

`r out["Supplementary Figure 6"]`

# Supplementary Figure 7 {.tabset}

`r out["Supplementary Figure 7"]`
