---
title: "miR34a asRNA cellular localization"
author: "Jason T. Serviss"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style> 
.caption { 
  color: Black; 
  font-family: "Times New Roman", Times, serif;
  font-size: 1.0em; 
}
</style>

```{r, echo = FALSE, message = FALSE}

packages <- c(
    "tidyverse",
    "printr",
    "ggthemes",
    "readr",
    "miR34AasRNAproject",
    "grid",
    "gtable"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)

```

```{r}

projectUrl <- "https://github.com/GranderLab/miR34a_asRNA_project/raw/master/inst"
dataUrl <- "https://github.com/GranderLab/miR34a_asRNA_project/raw/master/"

```

#### _Introduction_

<br></br>

#### _Methods_

<br></br>

#### _Results_

```{r}

url <- fileMap(type = "rds")["suppFigure1e"][[1]]
data <- read_rds(gzcon(url(file.path(dataUrl, url))))

#SK-N-SH has a larger proportion of GAPDH in the nucleus than cytoplasm
#The variation in miR34a asRNA expression is way too large for SK-MEL-5
#K562, HT1080, SK-N-DZ, and NCI-H460 have no or low miR34a asRNA expression
#use GAPDH instead of ACTB for cytoplasmic fraction, seems to be a better representation.

fdata <- data %>% 
  filter(!`Biosample term name` %in% c("K562", "HT1080", "SK-N-DZ", "NCI-H460", "SK-MEL-5", "SK-N-SH")) %>% 
  filter(gene_name != "ACTB") %>%
  select(`Biosample term name`, gene_id, gene_name, fraction, `Library made from`, `Biological replicate(s)`, TPM) %>%
  group_by(`Biosample term name`, gene_id, gene_name, fraction) %>%
  mutate(tmp = n() == 2) %>%
  filter(tmp | `Library made from` == "polyadenylated mRNA") %>%
  ungroup() %>%
  select(-tmp) %>%
  group_by(`Biosample term name`, gene_id, gene_name, `Biological replicate(s)`) %>%
  mutate(frac = TPM / sum(TPM)) %>%
  ungroup()

stats <- fdata %>%
  group_by(`Biosample term name`, gene_id, gene_name, fraction) %>%
  filter(n() == 2) %>%
  summarize(
    n = n(),
    mean = mean(frac),
    sd_min = mean(frac) + sd(frac),
    sd_max = mean(frac) - sd(frac)
  )  %>%
  ungroup()
```


```{r, fig.align='center', fig.height=8, fig.width=12, warning = FALSE}
markdown <- ggplot(data = NULL) +
  geom_point(
    data = stats,
    aes(x = gene_name, y = mean, color = fraction),
    position = position_dodge(width = 1)
  ) +
  facet_wrap(~`Biosample term name`, ncol = 1) +
  geom_errorbar(
    data = stats, 
    aes(x = gene_name, ymax = sd_max, ymin = sd_min, colour = fraction), 
    width = 0,
    position = position_dodge(width = 1)
  ) +
  scale_y_continuous(labels = scales::percent) +
  coord_flip() +
  labs(
    y = "% TPM",
    x = "Gene"
  ) +
  guides(colour = guide_legend(title = "Fraction"))

plotRmarkdown(markdown) +
  theme(
    legend.position = "top",
    axis.title.y = element_text(margin = margin(r = 20, "cm"))
  )

pdf <- ggplot(data = NULL) +
  geom_point(
    data = stats,
    aes(x = gene_name, y = mean, color = fraction),
    position = position_dodge(width = 1),
    size = 0.25
  ) +
  facet_wrap(~`Biosample term name`, ncol = 1) +
  geom_errorbar(
    data = stats, 
    aes(x = gene_name, ymax = sd_max, ymin = sd_min, colour = fraction), 
    width = 0,
    position = position_dodge(width = 1),
    size = 0.1
  ) +
  scale_y_continuous(labels = scales::percent) +
  coord_flip() +
  labs(
    y = "% TPM",
    x = "Gene"
  ) +
  guides(colour = guide_legend(title = "Fraction"))

figure <- plotPDF(pdf) +
  theme(
    axis.text.y = element_text(size = 4),
    strip.text.x = element_text(size = 5)
  )

path <- file.path("~/GitHub/miR34a_asRNA_project/inst", fileMap(type = "pdf")["suppFigure1e"][[1]])
ggsave(
 plot = figure,
 filename = path,
 device = cairo_pdf,
 height = 60,
 width = 83,
 units = "mm"
)
```

<div class="caption">
Write figure legend.
</div>

<br></br>

#### _Conclusions_

<br></br><br></br>
